# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M
  reservations:
    memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Blackbox prober exporter
  # https://github.com/prometheus/blackbox_exporter
  # ====================================================

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    deploy:
      mode: global
      resources: *x-exporter-resources-constraints
      placement:
        constraints:
          - node.role == worker
      labels:
        io.prometheus.role: "blackbox-exporter"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
    logging: *x-default-logging
    hostname: replica-{{.Task.Slot}}.blackbox-exporter.local
    networks:
      public:
      prometheus_gwnetwork:
        aliases:
          - blackbox-exporter.svc.cluster.local

networks:
  public: # The 3rd-party ingress network
    name: public
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
