version: '3'

includes:
  utils: ../../common/CatalystStack.AbstractTaskFile.yml

vars:
  STACK_NAME: 'promstack'

tasks:
  default:
    silent: true
    cmds:
    - task: utils:default

  create-manifest:
    cmds:
    - mkdir -p _tmp
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c blackbox-exporter/docker-stack.yml > _tmp/blackbox-exporter.manifest.yml"
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c cadvisor/docker-stack.{{ OS }}.yml > _tmp/cadvisor.manifest.yml"
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c grafana/docker-stack.yml > _tmp/grafana.manifest.yml"
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c node-exporter/docker-stack.yml > _tmp/node-exporter.manifest.yml"
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c prometheus/docker-stack.yml > _tmp/prometheus.manifest.yml"
    - "{{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} -c pushgateway/docker-stack.yml > _tmp/pushgateway.manifest.yml"

  create-deployment:
    deps: [create-manifest]
    cmds:
    - |
      {{.DOCKER_STACK_CONFIG}} {{.DOCKER_STACK_CONFIG_ARGS}} \
      -c _tmp/blackbox-exporter.manifest.yml \
      -c _tmp/cadvisor.manifest.yml \
      -c _tmp/grafana.manifest.yml \
      -c _tmp/node-exporter.manifest.yml \
      -c _tmp/prometheus.manifest.yml \
      -c _tmp/pushgateway.manifest.yml \
      > deployment.stack.yml
    - "sed 's|$(PWD)/||g' deployment.stack.yml > deployment.stack.yml.tmp"
    - rm deployment.stack.yml
    - mv deployment.stack.yml.tmp deployment.stack.yml

  deploy:
    cmds:
    - task: create-manifest
    - task: create-deployment
    - task: utils:external-networks
    - "docker stack deploy --with-registry-auth -c deployment.stack.yml {{.STACK_NAME}}"
