# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Blackbox exporter
# https://github.com/prometheus/blackbox_exporter
#
scrape_configs:
  - job_name: 'blackbox-exporter'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    honor_labels: true

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: replica-$1.blackbox-exporter.local:9115

      # Set hostname as instance label
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance
        replacement: $1:9115

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

      # Set node_name label to node hostname
      # This is useful for providing compatibility with the swarmprom dashboards
      - source_labels:
          - __meta_dockerswarm_node_hostname
        target_label: node_name
