# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-deploy: &x-deploy
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
    - node.role == manager

x-prometheus-subservice-deploy: &x-prometheus-subservice-deploy
  mode: global
  placement:
    # constraints:
    # - node.labels.services.promstack_prometheus_server == true
    max_replicas_per_node: 1

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Prometheus
  # https://github.com/prometheus/prometheus
  # ====================================================

  prometheus-server:
    image: prom/prometheus:v2.45.6
    command:
    - --config.file=/prometheus-configs.d/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    - --log.level=info
    user: "0:0"
    deploy:
      !!merge <<: *x-deploy
      labels:
        io.prometheus.role: "prometheus"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        traefik.enable: "true"
        traefik.http.routers.prometheus-insecure.entrypoints: web
        traefik.http.routers.prometheus-insecure.rule: Host(`prometheus.$INTERNAL_HOST`)
        traefik.http.services.prometheus.loadbalancer.server.port: "9090"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
    logging: *x-default-logging
    # ports:
    # - published: 9090
    #   target: 9090
    #   mode: host
    hostname: replica-{{.Task.Slot}}.prometheus.local
    networks:
      public:
      # aliases:
      # - prometheus.svc.cluster.local
      prometheus:
        aliases:
        - prometheus.local
      prometheus_gwnetwork:
        aliases:
        - prometheus.local
      prometheus_internal:
        aliases:
        - prometheus.internal
    extra_hosts:
    - "host.docker.internal:host-gateway"
    configs:
    - source: prometheus-prometheus
      target: /etc/prometheus/scrape-configs/prometheus.yml
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    - type: volume
      source: prometheus
      target: /prometheus
    - type: volume
      source: prometheus-configs
      target: /prometheus-configs.d
    depends_on:
    - prometheus

  prometheus:
    image: swarmlibs/genconfig:0.1.0-rc.1
    command:
    - --verbose
    - --file=/run/configs/prometheus.yml.tmpl
    - --out=/prometheus-configs.d/prometheus.yml
    environment:
    - PROMETHEUS_CLUSTER_NAME=${PROMETHEUS_CLUSTER_NAME:-{{ index .Service.Labels "com.docker.stack.namespace"}}}
    - PROMETHEUS_CLUSTER_REPLICA=${PROMETHEUS_CLUSTER_REPLICA:-replica-{{.Task.Slot}}}
    deploy:
      !!merge <<: *x-prometheus-subservice-deploy
      resources: *x-exporter-resources-constraints
    logging: *x-default-logging
    configs:
    - source: prometheus.yml.tmpl
      target: /run/configs/prometheus.yml.tmpl
    volumes:
    - type: volume
      source: prometheus-configs
      target: /prometheus-configs.d

  prometheus-config-provider:
    image: swarmlibs/prometheus-config-provider:0.1.0-rc.1
    command:
    - --output-dir=/prometheus-configs.d/scrape-configs
    deploy:
      !!merge <<: *x-prometheus-subservice-deploy
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "prometheus-config-provider"
      restart_policy:
        condition: any
        max_attempts: 15
        delay: 15s
        window: 10s
      rollback_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
    logging: *x-default-logging
    configs:
    - source: prometheus-dockerswarm-nodes
    - source: prometheus-dockerswarm-services-endpoints-host
    - source: prometheus-dockerswarm-services-endpoints-ingress
    - source: prometheus-dockerswarm-tasks
    # - source: prometheus-windows-exporters
    volumes:
    - type: volume
      source: prometheus-configs
      target: /prometheus-configs.d
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true

  prometheus-config-reloader:
    image: quay.io/prometheus-operator/prometheus-config-reloader:v0.74.0
    command:
    - --listen-address=:8080
    - --config-file=/prometheus-configs.d/prometheus.yml
    - --watched-dir=/prometheus-configs.d/scrape-configs
    - --reload-url=http://prometheus.internal:9090/-/reload
    - --runtimeinfo-url=http://prometheus.internal:9090/api/v1/status/runtimeinfo
    - --watch-interval=15s
    - --reload-timeout=10s
    deploy:
      !!merge <<: *x-prometheus-subservice-deploy
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "prometheus-config-reloader"
        io.prometheus.enabled: "true"
        io.prometheus.job_name: "prometheus-config-reloader"
        io.prometheus.scrape_port: "8080"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
      restart_policy:
        condition: any
        delay: 30s
        window: 15s
      rollback_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        monitor: 15s
        max_failure_ratio: 0.1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        monitor: 15s
        max_failure_ratio: 0.1
    logging: *x-default-logging
    networks:
      prometheus_internal:
    volumes:
    - type: volume
      source: prometheus-configs
      target: /prometheus-configs.d
    depends_on:
    - prometheus
    - prometheus-server
    - prometheus-config-provider

volumes:
  prometheus:
  prometheus-configs:

networks:
  public: # The 3rd-party ingress network
    name: public
    external: true
  prometheus:
    name: prometheus
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
  prometheus_internal:
    internal: true

configs:
  # Prometheus config files
  prometheus.yml.tmpl:
    name: prometheus.yml.tmpl-v1
    file: ./configs/prometheus.yml.tmpl
  prometheus-prometheus:
    name: prometheus-prometheus-v1
    file: ./configs/scrape-configs/prometheus.yml
    template_driver: golang

  # Prometheus's scrape config files
  prometheus-dockerswarm-nodes:
    name: prometheus-dockerswarm-nodes-v1
    file: ./configs/scrape-configs/dockerswarm-nodes.yml
    labels:
    - "io.prometheus.scrape_config=true"
  prometheus-dockerswarm-services-endpoints-host:
    name: prometheus-dockerswarm-services-endpoints-host-v1
    file: ./configs/scrape-configs/dockerswarm-services-endpoints-host.yml
    labels:
    - "io.prometheus.scrape_config=true"
  prometheus-dockerswarm-services-endpoints-ingress:
    name: prometheus-dockerswarm-services-endpoints-ingress-v1
    file: ./configs/scrape-configs/dockerswarm-services-endpoints-ingress.yml
    labels:
    - "io.prometheus.scrape_config=true"
  prometheus-dockerswarm-tasks:
    name: prometheus-dockerswarm-tasks-v1
    file: ./configs/scrape-configs/dockerswarm-tasks.yml
    labels:
    - "io.prometheus.scrape_config=true"
  prometheus-windows-exporter-tasks:
    name: prometheus-windows-exporter-tasks-v1
    file: ./configs/scrape-configs/windows-exporter.yml
    labels:
    - "io.prometheus.scrape_config=true"
