# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

x-deploy: &x-deploy
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager
      - node.labels.io.swarmlibs.promstack == true

services:

  # ====================================================
  # Grafana Dashboard
  # https://github.com/grafana/grafana
  # ====================================================

  grafana:
    image: swarmlibs/grafana:local
    deploy:
      <<: *x-deploy
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: "grafana"
        io.prometheus.scrape_port: "3000"
    logging: *x-default-logging
    ports:
      - published: 3000
        target: 3000
    hostname: grafana-{{.Task.Slot}}.svc.cluster.local
    networks:
      grafana:
      prometheus:
      dockerswarm_ingress:
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
      - type: volume
        source: grafana-provisioning-datasources
        target: /etc/grafana/provisioning/datasources

  grafana-config-provider:
    image: swarmlibs/prometheus-config-provider:main
    command:
      - --output-dir=/grafana-provisioning-datasources.d
      - --prometheus-scrape-config-label=io.grafana.provisioning.datasource
    deploy: *x-deploy
    logging: *x-default-logging
    volumes:
      - type: volume
        source: grafana-provisioning-datasources
        target: /grafana-provisioning-datasources.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

volumes:
  grafana-data:
  grafana-provisioning-datasources:

networks:
  grafana:
    # Internal network for Grafana services
  prometheus:
    name: prometheus
    external: true
  dockerswarm_ingress:
    name: dockerswarm_ingress
    external: true

configs:
  prometheus-datasource-v1:
    file: ./configs/prometheus.yml
    labels:
      - "io.grafana.provisioning.datasource=true"
