# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-exporter-resources-constraints: &x-exporter-resources-constraints
  limits:
    memory: 128M
  reservations:
    memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Prometheus Pushgateway
  # https://github.com/prometheus/pushgateway
  # ====================================================

  pushgateway:
    image: prom/pushgateway:latest
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      resources: *x-exporter-resources-constraints
      labels:
        io.prometheus.role: "pushgateway"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
    logging: *x-default-logging
    hostname: replica-{{.Task.Slot}}.pushgateway.local
    networks:
      public:
      prometheus_gwnetwork:
        aliases:
          - pushgateway.local

networks:
  public: # The 3rd-party ingress network
    name: public
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
