apiVersion: 1

datasources:
  - name: Prometheus (Promstack)
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    editable: false
    isDefault: true
